services:
  # Backend API (Docker)
  - type: web
    name: url-shortener-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: mysql-2b3b1439-sarkarabhisek50-d610.l.aivencloud.com
      - key: DB_PORT
        value: 22838
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        value: REPLACED_SEE_RENDER_DASHBOARD
      - key: DB_NAME
        value: defaultdb
      - key: JWT_SECRET
        value: REPLACED_SEE_RENDER_DASHBOARD
      - key: FRONTEND_URL
        value: https://url-shortener-frontend.onrender.com

  # Frontend (Docker + Nginx)
  - type: web
    name: url-shortener-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    dockerBuildArgs:
      - VITE_API_URL=https://url-shortener-0h1c.onrender.com
    envVars:
      - key: VITE_API_URL
        value: https://url-shortener-0h1c.onrender.com
